version: '1'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: business
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superprotectedpassword
    ports: 
      - 15432:5432
  consul:
    image: consul:1.15.4
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"
      - "8600:8600"