server.port : 8585

application:
  financeService:
    verificationEndpoint: /api/client/{clientId}/amount/{amountOverLast3Years}

spring :
  application:
    name: order-service
  sql:
    init:
      mode: always
  cloud:
    # disable consul
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: false
        hostname: localhost
  # pg connection
  datasource:
    url: jdbc:postgresql://localhost:15432/business
    username: admin
    password: superprotectedpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  config:
    import: 'consul:'

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      orderservice:
        register-health-indicator: true
        wait-duration-in-open-state: 1s
        failure-rate-threshold: 10
        record-exceptions:
          - java.net.ConnectException
          - org.springframework.web.client.HttpClientErrorException
  retry:
    instances:
      orderservice:
        maxAttempts: 2
        waitDuration: 200ms
        fail-after-max-attempts: true
